#!/bin/bash
# Helper script to save the map generated by SLAM Toolbox

if [ -z "$1" ]; then
    echo "Usage: ./save_map.sh <map_name>"
    echo "Example: ./save_map.sh office_map"
    exit 1
fi

MAP_NAME=$1
MAPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../maps" && pwd)"

if [ ! -d "$MAPS_DIR" ]; then
    mkdir -p "$MAPS_DIR"
fi

echo "Saving map to $MAPS_DIR/$MAP_NAME ..."
ros2 run nav2_map_server map_saver_cli -f "$MAPS_DIR/$MAP_NAME"
echo "Map saved successfully!"
